# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

os: osx
osx_image: xcode7.3
language: csharp
# If let by the gitignore.
#solution: ./****.sln

matrix:
  include:
    #- dotnet: 2.1.301
    #  mono: none
    #  env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest  # Already by default.

# Specified the branch.
branches:
  only:
    - master

# Environment variables
#env:
#  global:
#    - CODECOV_IO_TOKEN=2ff3d741-5b36-4314-9537-8581706ed054
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "GvFFGogMRSJvs5bJJN4flGmS1wj6Jv7ssl0hcRRaNXo3Uwb01sPUuD5yYMY1s1vkhsD8/XsN9Yv6N92A6XFPRZsDumEOD6TqlRdLsMr+63ltZ+nnxpTDCGr0oiFXH80g6iQl9PrXh3XEmCxQqggzMqVogIZ0/TT3DSnZq8dKyVugxscwYa+u/2Uf98AJgObGnooSYDJa8UNTvOVri8PhfIlvLinqM2nEbpvz3v+93/QbhLrsI/2G9bb6JK0Ny4WXw5k0mjH7r2Izcr9ux/mskFMbh7i0Xvtr3K0xUOoC4x/1a0HfXyZQu5hXDCDez8C0dV9/8XQSIug8wIBVbLk30ITTEZFVbI6w6Y8zNo3ZaaSfTxAKtChfa4HInQnpTeBMuncwF+k1uda/QlImY8LYCkF1ftL6AUKTb4Wk1uc0a0nkAzS8AXZvgrZi+SfbCZJklK/2vtzKvoLtYeDX/A0eQ4ZtVfpnQS0/XyQj5LnJJtTsOYFzMUQwsEIWSOoK1r0PBx5lHoFGPZllehPpjqdfl6khUG1mqwaolfAHBD97G4e5jFT66+p0oKhRSw+2T4mOmgVdrv6PK//JkKb4ViFK2sYHj8U8Ekexxjbdx7DtR+ImQKVHoOnMp0UehMNDbKwLUSowBSuK15WQr7nrqBFULc128810TTwrEwuWYmhSeWg="

addons:
  apt:
    packages:
      - xsltproc
      - xmlstarlet
  sonarcloud:
    organization: "graygzou-github"
    token:
      secure: ${SONAR_TOKEN}
  coverity_scan:
    project:
      name: "Graygzou/Unity-CI-Template"
      description: "Sample project for Travis and Nunit testing"
    build_command_prepend: ./Scripts/install.sh
    build_command: ./Scripts/build.sh
    branch_pattern: master

# Set up prerequisites for installing dependencies that you need for you build.
# For example:
#   npm install
#   bundle install
before_install:
  # Nuget installs
  ### The NUnit unit testing tool.
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory packages -Verbosity quiet
  - nuget install NUnit.Runners -Version 3.8.0 -OutputDirectory testrunner -Verbosity quiet
  ### (Windows OSs only - no MONO) OpenCover captures the NUnit testing results and produces the coverage report in .XML format
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory packages -Verbosity quiet
  ### Produces the HTML report based upon OpenCover’s Results (.XML)
  - nuget install ReportGenerator -Version 2.4.5.0 -OutputDirectory packages
  - nuget install coveralls.io -Version 1.4.2 -OutputDirectory coveralls
  - nuget install JetBrains.dotCover.CommandLineTools -Version 2018.1.1 -OutputDirectory packages -Verbosity quiet
  # Apt installs
  - brew update > /dev/null
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get update;
      sudo apt-get install xmlstarlet;
    else
      brew update;
      brew install xmlstarlet;
    fi
  # Make executable files
  - chmod a+x ./Scripts/*.sh
  - chmod a+x ./packages/OpenCover.4.6.519/tools/OpenCover.Console.exe
  - chmod a+x ./packages/JetBrains.dotCover.CommandLineTools.2018.1.1/tools/dotCover.exe
  # Coverity scan
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

# Set up the dependencies of your build.
install:
  - ./Scripts/install.sh
  - ./Scripts/build.sh

# Set up your environment before you run your script.
# For example:
#   copy files, start your database, or declare environment variables
before_script:

# Runs your test script
script:
  # Run customs tests.
  - ./Scripts/run-tests.sh

  # Try something new.... Does not work.
  #- mono --debug --profile=monocov:outfile=monocovCoverage.cov,+Unity-CI-Template ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe --process=Single ./Assets/Library/ScriptAssemblies/Assembly-CSharp.dll
  #- monocov --export-xml=monocovCoverage monocovCoverage.cov
  #- cat monocovCoverage.cov

  # Try convert Unity xml response into NUnit xml.
  #- ./Scripts/fix-unity-test-results.sh
  #- echo "Done"
  # done
  #- ./Scripts/nunit.sh ./Library/ScriptAssemblies/Assembly-CSharp-Editor.dll
  # OpenCover -- Not tested
  #- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\MyUnitTests\bin\Debug\MyUnitTests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
  #- codecov -f "MyProject_coverage.xml
  # -----------------------
  # NUnit tests
  # -----------------------
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  # --- DEBUG ---
  - ./Scripts/debug.sh
  # Not supported with NUnit 2
  # ...
  # New Test => Cause build to fail.
  # - ./Scripts/test.sh
  # Test with NUnit 3
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Library/ScriptAssemblies/Assembly-CSharp-Editor.dll
  - ./codecov -f $(pwd)/TestResult.xml -t $CODECOV_IO_TOKEN
  # ------------------------
  # End
  # ------------------------

# The deployment portion is used to deploy to specific,
# supported hosts, like S3, Heroku, or GitHub Releases.
#after_success:

# Build Matrix
# Creating a build matrix is a way for us to test a wide variety of environments.

# set notification options
notifications:
  email:
    recipients:
      - boiron.greg@gmail.com
    on_success: change # Default: change. Can be replace by never.
    on_failure: always # Default: always
