version: '1.0.0.{build}'
image: Visual Studio 2017

environment:
  CYG_ROOT: C:\cygwin64

install:
  - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./Scripts/install.sh"'
build_script:
  - '%CYG_ROOT%/bin/bash -lc "cd $QPPVEYOR_BUILD_FOLDER; ./Scripts/build.sh"'

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov

build:
  project: Unity-CI-Template.sln
  # Verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.exe" -targetargs:".\Library\ScriptAssemblies\Assembly-CSharp.dll -noshadow" -filter:"+[UnityPackageManager*]*" -output:".\MyProject_coverage.xml" 
  - codecov -f "MyProject_coverage.xml"

